### ISSUE TITLE
Getting an Internal Server Error

### ISSUE THREAD

**Issue by surajhhss1993** [deadnight7/saikiranBookstoreApp#2]
Hi Chirag,
Thanks for providing the project. I was able to run this on Netbeans. I followed your tutorial, the application opened, but I am getting an error:

Error Status 500 - Internal Server Error!!

Please find the attached image. 
Can you please help me? I need this project to be submitted ASAP. 
![saikiran enterprises](https://cloud.githubusercontent.com/assets/24260927/20736289/914019aa-b6cb-11e6-9188-e577f3e9224a.PNG)

I thank you for all your help in advance!! :)

**Comment by deadnight7** [comment]
Please check whether you have configured your mysql dbs

**Comment by deadnight7** [comment]
Hi All,
It would be helpful if you contribute yourself in understanding the architecture for this project and help fix the configuration issues like these by yourself, Plagiarism wont lead you anywhere (to all academic folks). 

Also note - I am not monitoring this project due to my lack of time, Unless there is an appropriate defect  in application logic. Will not be able to spend time working on it closely.

Regards,
Chirag Pandit

**Comment by surajhhss1993** [comment]
It was solved a long time ago. Thanks anyway for following up.
Did not get time to close the issue, my bad!!
